#Git Alias
alias glog='git log'
alias glg='git lg'
alias gs='git status'
alias gc='git commit'
alias gcm='gc -m'
alias gadd='git add'
alias gadda='git add -A'
alias ga='gadda'
alias gpl='git pull'
alias gph='git push'
alias gfetch='git fetch'
alias gcheck='git checkout'
