#!/bin/sh

# Load libs
. $(dirname $(realpath $0))/lib.sh

# Show Help Info
if [ "$1" = "-h" ] || [ "$1" = "--help" ];then
    echo "Usage: ${0##*/} [-n|--name] [-a|--all] [-r|--reverse] [-o|--original] REGEX"
    echo "Find resource"
    exit 0
fi

# Find resource
find_resource $@

