#!/bin/sh

# Load libs
. $(dirname $(realpath $0))/lib.sh

# Show Help Info
if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ];then
    echo "Usage: ${0##*/} [-i] TOOL [OPTION]..."
    echo "Quick edit install-tool"
    exit 0
fi

# Set Paramters
TOOL="$*"
has nano && EDITOR="nano"
has vi && EDITOR="vi"
has vim && EDITOR="vim"

# Pre Edit: Set Params
if [ "${TOOL##*.}" = "list" ];then
    TOOL_PATH="$(realpath $DOTFILE_HOME/list/$TOOL)"
else
    [ "${TOOL##*.}" = "sh" ] \
        && TOOL=install_$TOOL \
        || TOOL=install_$TOOL.sh
    TOOL_PATH="$(realpath $DOTFILE_HOME/script/$TOOL)"
fi
[ ! -f "$TOOL_PATH" ] && IS_NEW_TOOL=yes

# Pre Edit: Backup
mkdir -p "$TMP_PATH/tool"
[ -z "$IS_NEW_TOOL" ] \
    && cp -a "$TOOL_PATH" "$TMP_PATH/tool/$TOOL.old"

# Edit
$EDITOR "$TOOL_PATH"

#Post Edit
if [ -n "$IS_NEW_TOOL" ]; then
    [ -f "$TOOL_PATH" ] \
        && chmod +x "$TOOL_PATH" \
        && echo "Created new tool: $TOOL ($TOOL_PATH)" \
        || echo "Canceled."
else
    [ -n "$(diff -q $TMP_PATH/tool/$TOOL.old $TOOL_PATH)" ] \
        && echo "Updated tool: $TOOL ($TOOL_PATH)" \
        || echo "No modification made"
fi
