#!/bin/bash

# Load libs
. $(dirname $(realpath $0))/lib.sh

# Show Help Info
if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ];then
    echo "Usage: ${0##*/} [-i] TOOL [OPTION]..."
    echo "Remove tool"
    exit 0
fi

# Remove tool
remove_tool $@ || {
    echo "An error occured while removing '$@'."
    exit 1
}

