#!/bin/sh

cd $(dirname $(realpath $0))/..

# Show Help Info
if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ];then
    echo "Usage: ${0##*/} [-i] TOOL..."
    echo "Install tools"
    exit 0
fi

# Read command line arguments
[ "$1" = "-i" ] && { INTERACTIVE='-i'; shift; } || { INTERACTIVE=''; }

# Install tools
for TOOL in $@
do
    bin/tool-install $INTERACTIVE $TOOL || {
        echo 'Batch install stopped.'
        exit 1
    }
done
