#!/bin/bash

# Load libs
. $(dirname $(realpath $0))/lib.sh

[ -z "$*" ] && {
    echo "Usage: ${0##*/} TOOL..."
    echo "Test tools"
    echo "Use \`\$TOOL_TEST_CMD\` to test every TOOL"
    echo "Use \`{}\` to replace the TOOL to test ({} => TOOL)";
    exit 0
}

[ -z "$TOOL_TEST_CMD" ] && {
    echo "Please set environment variable '\$TOOL_TEST_CMD'!";
    echo "Tip: Use \`{}\` to replace the TOOL to test ({} => TOOL)";
    exit 1;
}

LOG_DIR="$TMP_PATH/tool-test-log"

mkdir -p "$LOG_DIR"
rm -f $LOG_DIR/*.log

for TOOL in $@
do
    CMD="$(echo "$TOOL_TEST_CMD"|sed "s/{}/$TOOL/g")"
    echo "+ $CMD"
    echo -n "Testing '$TOOL'... " \
        && bash -c "$CMD" \
            > "$LOG_DIR/$TOOL.log" \
        && rm "$LOG_DIR/$TOOL.log" \
        && echo passed. \
        || echo failed.
done

[ -n "`ls $LOG_DIR`" ] && {
    echo -e "\nSome tests failed, logs saved in:"
    ls -1 $LOG_DIR | sed "s:^: - $LOG_DIR/:"
} || {
    echo -e "\nAll Test Passed."
}

